name: Auto-label PR for Release Branches

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'release/*'

jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply "release" label to PRs
        uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true