name: Update Feature Flags Documentation with Comparison

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Get Latest Release Branch
        id: get-latest-release
        run: |
          # Get the latest release branch matching "release/*"
          latest_release=$(git branch -r --sort=-committerdate | grep 'origin/release/' | head -n 1 | sed 's|origin/||')
          echo "Latest release branch: $latest_release"
          echo "branch=$latest_release" >> $GITHUB_OUTPUT

      - name: Read Feature Flags from Latest Release Branch
        id: read-release-flags
        run: |
          FILE_PATH="./src/contexts/featureFlags/FeatureFlagContext.tsx"

          # Checkout the latest release branch and read FeatureFlagMapping content
          git checkout ${{ steps.get-latest-release.outputs.branch }}
          
          node -e "
            const fs = require('fs');
            const content = fs.readFileSync('$FILE_PATH', 'utf8');
            const regex = /export const FeatureFlagMapping =\\s*{([\\s\\S]+?)}/;
            const match = content.match(regex);

            if (!match || !match[1]) {
              console.error('FeatureFlagMapping object not found in release branch');
              process.exit(1);
            }

            const objectContent = '{' + match[1].trim() + '}';
            const FeatureFlagMapping = eval('(' + objectContent + ')');
            fs.writeFileSync(process.env.GITHUB_OUTPUT, `flags=${JSON.stringify(FeatureFlagMapping)}`, { flag: 'a' });
          "


      - name: Read Feature Flags from Main Branch
        id: read-main-flags
        run: |
          FILE_PATH="./src/contexts/featureFlags/FeatureFlagContext.tsx"

          # Checkout the main branch and read FeatureFlagMapping content
          git checkout main
          
          node -e "
            const fs = require('fs');
            const content = fs.readFileSync('$FILE_PATH', 'utf8');
            const regex = /export const FeatureFlagMapping =\\s*{([\\s\\S]+?)}/;
            const match = content.match(regex);

            if (!match || !match[1]) {
              console.error('FeatureFlagMapping object not found in main branch');
              process.exit(1);
            }

            const objectContent = '{' + match[1].trim() + '}';
            const FeatureFlagMapping = eval('(' + objectContent + ')');
            fs.writeFileSync(process.env.GITHUB_OUTPUT, `flags=${JSON.stringify(FeatureFlagMapping)}`, { flag: 'a' });
          "

      - name: Generate Comparison Markdown
        id: generate-markdown
        run: |
          const releaseFlags = JSON.parse('${{ steps.read-release-flags.outputs.flags }}');
          const mainFlags = JSON.parse('${{ steps.read-main-flags.outputs.flags }}');
          const releaseBranch = '${{ steps.get-latest-release.outputs.branch }}';

          let markdownContent = `# Feature Flags Documentation\n\n`;
          markdownContent += `> **Comparison between \`main\` and \`${releaseBranch}\`**\n\n`;
          markdownContent += '| Count | Key         | Release Value (`' + releaseBranch + '`) | Main Value   | Status           |\n';
          markdownContent += '|-------|-------------|-------------------------|--------------|------------------|\n';

          let count = 1;
          const allKeys = new Set([...Object.keys(releaseFlags), ...Object.keys(mainFlags)]);

          for (const key of allKeys) {
            const releaseValue = releaseFlags[key] !== undefined ? releaseFlags[key] : 'N/A';
            const mainValue = mainFlags[key] !== undefined ? mainFlags[key] : 'N/A';

            let status = 'Unchanged';
            if (releaseValue === 'N/A') {
              status = 'New 🔵';
            } else if (mainValue === 'N/A') {
              status = 'Removed 🔴';
            } else if (releaseValue !== mainValue) {
              status = 'Updated 🟡';
            } else {
              status = 'Unchanged ⚪';
            }

            markdownContent += `| ${count}     | ${key} | \`${releaseValue}\`      | \`${mainValue}\`     | **${status}** |\n`;
            count++;
          }

          const outputPath = './FEATURE_FLAGS.md';
          require('fs').writeFileSync(outputPath, markdownContent);
        env:
          NODE_ENV: 'production'

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add FEATURE_FLAGS.md
          git commit -m "Update feature flags documentation with comparison"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
