name: Re-Check Cherry-Pick on New PRs

on:
  pull_request_target:
    branches:
      - release/*  # Trigger when new PRs are raised on any release branch

jobs:
  recheck-cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Re-Run Workflow on Related PRs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const { data: pulls } = await octokit.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              base: context.payload.pull_request.base.ref,
            });

            for (const pr of pulls) {
              console.log(`Re-running workflow for PR: ${pr.html_url}`);
              await octokit.rest.actions.reRunWorkflow({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: pr.id,
              });
            }
