name: Re-Check Cherry-Pick on New PRs

on:
  pull_request_target:
    branches:
      - release/*  # Trigger when new PRs are raised on any release branch

jobs:
  recheck-cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Re-Run Workflow on Related PRs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;

            // List all open PRs on the target branch
            const pulls = await octokit.rest.pulls.list({
              owner,
              repo,
              state: 'open',
              base: context.payload.pull_request.base.ref,
            });

            for (const pr of pulls.data) {
              console.log(`Re-running workflow for PR: ${pr.html_url}`);
              
              // Trigger a re-run for the relevant workflow
              await octokit.rest.actions.reRunWorkflow({
                owner,
                repo,
                run_id: pr.id,  // Workflow run ID to re-run
              });
            }
