name: Re-Check Cherry-Pick on New PRs

on:
  pull_request_target:
    branches:
      - release/*  # Trigger when new PRs are raised on any release branch

jobs:
  recheck-cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: List Open Pull Requests on the Target Branch
        run: |
          echo "Listing open PRs on branch: ${{ github.event.pull_request.base.ref }}"

          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=${{ github.event.pull_request.base.ref }}" \
            | jq '.[] | {html_url: .html_url, number: .number}'

      - name: Re-Run Workflows for Related Pull Requests
        run: |
          echo "Re-running workflows for PRs on branch: ${{ github.event.pull_request.base.ref }}"

          PRS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=${{ github.event.pull_request.base.ref }}" \
            | jq '.[].number')

          for pr_number in $PRS; do
            echo "Re-running workflow for PR #$pr_number"
            
            RUN_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs" \
              | jq ".workflow_runs[] | select(.pull_requests[].number == $pr_number) | .id" | head -n 1)

            if [ -n "$RUN_ID" ]; then
              curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github+json" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/rerun"
              echo "Workflow re-run triggered for PR #$pr_number"
            else
              echo "No workflow run found for PR #$pr_number"
            fi
          done
