name: Compare JSON Files

on:
  workflow_dispatch:
    inputs:
      old_url:
        description: "URL of the old JSON file"
        required: true
      new_url:
        description: "URL of the new JSON file"
        required: true
      environment:
        description: "Environment (e.g., Dev, Prod)"
        required: true
      lob:
        description: "Line of Business (LOB)"
        required: true

jobs:
  compare-json:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Required Packages
        run: |
          npm install node-fetch@2 exceljs json2csv    

      - name: Run JSON Comparison Script
        env:
          OLD_URL: ${{ github.event.inputs.old_url }}
          NEW_URL: ${{ github.event.inputs.new_url }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          LOB: ${{ github.event.inputs.lob }}
        run: |
          node -e "
            const fetch = require('node-fetch');
            const ExcelJS = require('exceljs');
            const { Parser } = require('json2csv');
            const fs = require('fs');

            async function fetchJson(url) {
              const response = await fetch(url);
              if (!response.ok) throw new Error('Failed to fetch JSON');
              return await response.json();
            }

            async function compareJson() {
              const oldData = await fetchJson(process.env.OLD_URL);
              const newData = await fetchJson(process.env.NEW_URL);
              const environment = process.env.ENVIRONMENT;
              const lob = process.env.LOB;

              const workbook = new ExcelJS.Workbook();
              const dataByParentKey = {};

              function processParentKey(parentKey, oldObj, newObj) {
                const newEntries = [];
                const notFoundEntries = [];
                const differentEntries = [];

                const oldKeys = Object.keys(oldObj);
                const newKeys = Object.keys(newObj);

                // Determine new, not found, and different entries
                oldKeys.forEach((key) => {
                  if (!newObj[key]) {
                    notFoundEntries.push({ key, ...oldObj[key] });
                  } else if (JSON.stringify(oldObj[key]) !== JSON.stringify(newObj[key])) {
                    // Add the old and new values in separate rows with merged key column
                    const diffRows = [
                      { key, ...oldObj[key], diff_type: `${environment} ${lob} - Old Value` },
                      { key: '', ...newObj[key], diff_type: `${environment} ${lob} - New Value` }
                    ];
                    differentEntries.push(...diffRows);
                  }
                });

                newKeys
                  .filter((key) => !oldKeys.includes(key))
                  .forEach((key) => newEntries.push({ key, ...newObj[key] }));

                // Save categorized data by parent key
                dataByParentKey[parentKey] = {
                  newEntries,
                  notFoundEntries,
                  differentEntries,
                };
              }

              // Process each parent key dynamically
              Object.keys(oldData).forEach((parentKey) => {
                const oldObj = oldData[parentKey];
                const newObj = newData[parentKey] || {};
                processParentKey(parentKey, oldObj, newObj);
              });

              Object.keys(newData)
                .filter((parentKey) => !oldData.hasOwnProperty(parentKey))
                .forEach((parentKey) => {
                  const newObj = newData[parentKey];
                  processParentKey(parentKey, {}, newObj);
                });

              // Generate Excel and CSV outputs for each parent key
              for (const [parentKey, { newEntries, notFoundEntries, differentEntries }] of Object.entries(dataByParentKey)) {
                const sheet = workbook.addWorksheet(parentKey);

                // Helper function to get all dynamic column headers
                const getAllHeaders = (entries) => {
                  const headers = new Set();
                  entries.forEach(entry => {
                    Object.keys(entry).forEach(header => headers.add(header));
                  });
                  return Array.from(headers);
                };

                // Add New Entries Table
                if (newEntries.length > 0) {
                  sheet.addRow(['New Entries']);
                  const headers = getAllHeaders(newEntries);
                  sheet.columns = headers.map(header => ({ header, key: header }));
                  sheet.addRows(newEntries);
                  sheet.addRow([]); // Blank row for spacing
                } else {
                  sheet.addRow(['No New Entries']);
                  sheet.addRow([]);
                }

                // Add Not Found Entries Table
                if (notFoundEntries.length > 0) {
                  sheet.addRow(['Not Found Entries']);
                  const headers = getAllHeaders(notFoundEntries);
                  sheet.columns = headers.map(header => ({ header, key: header }));
                  sheet.addRows(notFoundEntries);
                  sheet.addRow([]); // Blank row for spacing
                } else {
                  sheet.addRow(['No Not Found Entries']);
                  sheet.addRow([]);
                }

                // Add Different Entries Table
                if (differentEntries.length > 0) {
                  sheet.addRow(['Different Entries']);
                  const headers = getAllHeaders(differentEntries);
                  sheet.columns = headers.map(header => ({ header, key: header }));
                  differentEntries.forEach((entry) => sheet.addRow(entry));
                  sheet.addRow([]); // Blank row for spacing
                } else {
                  sheet.addRow(['No Different Entries']);
                  sheet.addRow([]);
                }

                // Create CSV for each parentKey
                const parser = new Parser();
                if (newEntries.length > 0) fs.writeFileSync(`json_csv_outputs/${parentKey}_new_entries.csv`, parser.parse(newEntries));
                if (notFoundEntries.length > 0) fs.writeFileSync(`json_csv_outputs/${parentKey}_not_found_entries.csv`, parser.parse(notFoundEntries));
                if (differentEntries.length > 0) fs.writeFileSync(`json_csv_outputs/${parentKey}_different_entries.csv`, parser.parse(differentEntries));
              }

              await workbook.xlsx.writeFile('json_differences.xlsx');
              console.log('Excel and CSV files generated successfully.');
            }

            compareJson().catch((error) => {
              console.error('Error:', error);
              process.exit(1);
            });
          "

      - name: Upload Excel Output
        uses: actions/upload-artifact@v4
        with:
          name: JSON Comparison Report
          path: json_differences.xlsx

      - name: Upload CSV Outputs
        uses: actions/upload-artifact@v4
        with:
          name: JSON Comparison CSVs
          path: 'json_csv_outputs/*.csv'
