name: Update README with Auto-Merge PR

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to update'
        required: false
        default: 'release/1.0.0'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create a new branch
        run: |
          TEMP_BRANCH="update-readme-branch-${{ github.run_id }}"
          git checkout -b $TEMP_BRANCH
          echo "Adding random text to README.md file" >> README.md
          echo "Random text: $RANDOM" >> README.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with random text"
          git push origin $TEMP_BRANCH

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: $TEMP_BRANCH
          base: ${{ github.event.inputs.branch || 'release/1.0.0' }}
          title: "Auto-update README with random text"
          body: "This PR updates README.md with random text."
          labels: auto-merge

      - name: Auto-approve and merge PR
        if: success() && steps.create_pr.outputs.pull-request-url != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const pr_number = parseInt("${{ steps.create_pr.outputs.pull-request-number }}");
            await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              event: 'APPROVE',
              body: 'Auto-approved by GitHub Actions'
            });
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              merge_method: 'squash'
            });
