name: Update README

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to update'
        required: false
        default: 'master'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set branch name
        id: branch_name
        run: echo "branch_name=${{ github.event.inputs.branch || 'master' }}" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          echo "Adding random text to README.md file" >> README.md
          echo "Random text: $RANDOM" >> README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with random text"

      - name: Push changes
        env:
          BRANCH_NAME: ${{ env.branch_name }}
        run: |
          git push origin $BRANCH_NAME
