name: New Compare JSON Files

on:
  workflow_dispatch:
    inputs:
      old_url:
        description: "URL of the old JSON file"
        required: false
      old_environment:
        description: "Environment for the old JSON file"
        required: true
        type: choice
        options:
          - test
          - stage
          - prod
        default: test
      old_lob:
        description: "Line of Business (LOB) for the old JSON file"
        required: true
        type: choice
        options:
          - eni
          - mnr
          - cns
          - ifp
        default: cns
      new_url:
        description: "URL of the new JSON file"
        required: false
      new_environment:
        description: "Environment for the new JSON file"
        required: true
        type: choice
        options:
          - test
          - stage
          - prod
        default: test
      new_lob:
        description: "Line of Business (LOB) for the new JSON file"
        required: true
        type: choice
        options:
          - eni
          - mnr
          - cns
          - ifp
        default: cns

jobs:
  compare-json:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install exceljs axios    

      - name: Run JSON Comparison Script
        env:
          OLD_URL: ${{ github.event.inputs.old_url }}
          OLD_ENVIRONMENT: ${{ github.event.inputs.old_environment }}
          OLD_LOB: ${{ github.event.inputs.old_lob }}
          NEW_URL: ${{ github.event.inputs.new_url }}
          NEW_ENVIRONMENT: ${{ github.event.inputs.new_environment }}
          NEW_LOB: ${{ github.event.inputs.new_lob }}
        run: |
          node -e "
            const axios = require('axios');
            const ExcelJS = require('exceljs');
            const fs = require('fs');

            const excludedKeys = ['smartling', 'lagoon.updatedBy', 'lagoon.updatedAt', 'id'];
            const oldEnvironment = process.env.OLD_ENVIRONMENT;
            const oldLob = process.env.OLD_LOB;
            const newEnvironment = process.env.NEW_ENVIRONMENT;
            const newLob = process.env.NEW_LOB;

            const OLD_JSON = oldLob;
            const NEW_JSON = newLob;

            async function loadJsonFromUrlOrFile(url, filePath) {
              if (url) {
                const response = await axios.get(url);
                return response.data;
              } else {
                return JSON.parse(fs.readFileSync(filePath, 'utf8'));
              }
            }

            async function compareJson() {
              const oldData = await loadJsonFromUrlOrFile('', 'old_data.json');
              const newData = await loadJsonFromUrlOrFile('', 'new_data.json');

              const workbook = new ExcelJS.Workbook();

              function removeExcludedKeys(obj) {
                const cleanedObj = {};
                Object.keys(obj).forEach((key) => {
                  if (!excludedKeys.includes(key)) {
                    cleanedObj[key] = obj[key];
                  }
                });
                return cleanedObj;
              }

              function createSheetForMissingParent(workbook, parentKey, type) {
                const sheet = workbook.addWorksheet(`${type} ${parentKey}`);
                const headerRow = sheet.addRow([`${type} Parent Key: ${parentKey}`]);
                headerRow.font = { bold: true };
              }

              Object.keys(oldData).forEach((parentKey) => {
                if (!newData[parentKey]) {
                  createSheetForMissingParent(workbook, parentKey, 'Missing in New JSON');
                }
              });

              Object.keys(newData).forEach((parentKey) => {
                if (!oldData[parentKey]) {
                  createSheetForMissingParent(workbook, parentKey, 'Missing in Old JSON');
                }
              });

              for (const parentKey of Object.keys(oldData)) {
                const oldObj = oldData[parentKey];
                const newObj = newData[parentKey] || {};
                const sheet = workbook.addWorksheet(parentKey.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 31));

                const parentHeaderRow = sheet.addRow([`Parent Key: ${parentKey}`]);
                parentHeaderRow.font = { bold: true };
                sheet.addRow([]);

                const newEntries = [];
                const notFoundEntries = [];
                const differentEntries = [];
                const similarEntries = [];

                const oldKeys = Object.keys(oldObj);
                const newKeys = Object.keys(newObj);

                oldKeys.forEach((key) => {
                  const cleanedOld = removeExcludedKeys(oldObj[key]);
                  const cleanedNew = removeExcludedKeys(newObj[key] || {});

                  if (!newObj[key]) {
                    notFoundEntries.push({ source: 'Old JSON', key, ...cleanedOld });
                  } else if (JSON.stringify(cleanedOld) !== JSON.stringify(cleanedNew)) {
                    differentEntries.push(
                      { source: 'Old JSON', key, ...cleanedOld },
                      { source: 'New JSON', key: '', ...cleanedNew }
                    );
                  } else {
                    similarEntries.push({ source: 'Old JSON and New JSON', key, ...cleanedOld });
                  }
                });

                newKeys
                  .filter((key) => !oldKeys.includes(key))
                  .forEach((key) => {
                    const cleanedNew = removeExcludedKeys(newObj[key]);
                    newEntries.push({ source: 'New JSON', key, ...cleanedNew });
                  });

                // Add data sections to the sheet
                if (newEntries.length) {
                  const header = sheet.addRow(['New Entries']);
                  header.font = { bold: true };
                  sheet.addRows(newEntries);
                }

                if (notFoundEntries.length) {
                  const header = sheet.addRow(['Not Found Entries']);
                  header.font = { bold: true };
                  sheet.addRows(notFoundEntries);
                }

                if (differentEntries.length) {
                  const header = sheet.addRow(['Different Entries']);
                  header.font = { bold: true };
                  sheet.addRows(differentEntries);
                }

                if (similarEntries.length) {
                  const header = sheet.addRow(['Similar Entries']);
                  header.font = { bold: true };
                  sheet.addRows(similarEntries);
                }
              }

              await workbook.xlsx.writeFile('json_differences.xlsx');
              console.log('Excel file generated successfully.');
            }

            compareJson().catch((error) => {
              console.error('Error:', error);
              process.exit(1);
            });
          "

      - name: Upload Excel Output
        uses: actions/upload-artifact@v4
        with:
          name: JSON Comparison Report
          path: json_differences.xlsx
